### ISSUE TITLE
Module 'nodes' has no attribute 'InpaintModelConditioning'

### ISSUE THREAD

**Issue by Alphyn-gunner** [Acly/comfyui-inpaint-nodes#23]
I get this error when trying to use the example workflow for the Inpaint Model Conditioning with SDXL. I also get it when trying to use SDXL inpaint in Krita AI Diffusion. 
I have a very rudimentary understanding of python, and after checking the contents of nodes.py I see that indeed InpaintModelConditioning is mentioned only once, it's called but never defined.

**Comment by Alphyn-gunner** [comment]
Example log
```
gc collect
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    outputs[unique_id] = output_data
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    return results
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 199, in encode
    positive, negative, latent = nodes.InpaintModelConditioning().encode(
AttributeError: module 'nodes' has no attribute 'InpaintModelConditioning'
```

**Comment by Latentnaut** [comment]
Not related with your issue... but I am curious: is this pack compatible with krita?

**Comment by Acly** [comment]
Yes! InpaintModelConditioning is part of base ComfyUI. If it can't be found ComfyUI version is probably too old.
