### ISSUE TITLE
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by Song367** [Acly/comfyui-inpaint-nodes#40]
lama:  E:\workplace\ComfyUI\models\inpaint\big-lama.pt
!!! Exception during processing!!! PytorchStreamReader failed locating file constants.pkl: file not found
Traceback (most recent call last):
  File "E:\workplace\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\workplace\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\workplace\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\workplace\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 312, in load
    sd = torch.jit.load(model_file, map_location="cpu").state_dict()
  File "E:\workplace\ComfyUI\venvs\lib\site-packages\torch\jit\_serialization.py", line 159, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

**Comment by PerrySm** [comment]
I have the same issue with constants.pkl on the LaMa Inpainting Node

**Comment by NiuRou520** [comment]
Is there a professional answer to this?

**Comment by Acly** [comment]
No idea apart from trying to re-download the file. Sounds like it's incomplete/corrupt.
