### ISSUE TITLE
import error , ModuleNotFoundError: No module named 'comfy_extras.chainner_models.types'

### ISSUE THREAD

**Issue by whmc76** [Acly/comfyui-inpaint-nodes#53]
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-inpaint-nodes\__init__.py", line 21, in <module>
    from . import nodes
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 14, in <module>
    from comfy_extras.chainner_models.types import PyTorchModel
ModuleNotFoundError: No module named 'comfy_extras.chainner_models.types'

Cannot import E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-inpaint-nodes module for custom nodes: No module named 'comfy_extras.chainner_models.types'

**Comment by Acly** [comment]
please update...
