### ISSUE TITLE
No module named 'comfy_extras.chainner_models.types'

### ISSUE THREAD

**Issue by Wladislav** [Acly/comfyui-inpaint-nodes#55]
Hello, please help me with this error. What can I do to make it go away?

[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\__init__.py", line 21, in <module>
    from . import nodes
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 14, in <module>
    from comfy_extras.chainner_models.types import PyTorchModel
ModuleNotFoundError: No module named 'comfy_extras.chainner_models.types'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes module for custom nodes: No module named 'comfy_extras.chainner_models.types'

**Comment by Wladislav** [comment]
> Hello, please help me with this error. What can I do to make it go away?
> Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes module for custom nodes: No module named 'comfy_extras.chainner_models.types'

Reinstallation comfyui-inpaint-nodes helped solve the problem
