### ISSUE TITLE
Open CV errors when using mask infill    Unrecognized or unsupported array type in function 'cvGetMat'

### ISSUE THREAD

**Issue by NicTanghe** [Acly/comfyui-inpaint-nodes#62]
!!! Exception during processing!!! OpenCV(4.10.0) /io/opencv/modules/core/src/array.cpp:2494: error: (-206:Bad flag (parameter or structure field)) Unrecognized or unsupported array type in function 'cvGetMat'

Traceback (most recent call last):
  File "/home/tanghe/tools/comfy/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/tanghe/tools/comfy/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/tanghe/tools/comfy/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/tanghe/tools/comfy/ComfyUI/custom_nodes/comfyui-inpaint-nodes/nodes.py", line 253, in fill
    filled_np = cv2.inpaint(
cv2.error: OpenCV(4.10.0) /io/opencv/modules/core/src/array.cpp:2494: error: (-206:Bad flag (parameter or structure field)) Unrecognized or unsupported array type in function 'cvGetMat'

**Comment by Acly** [comment]
Looks like a mistake in yesterday's changes, should work again now after update.
