### ISSUE TITLE
TypeError: ApplyFooocusInpaint._input_block_patch() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by 748226917** [Acly/comfyui-inpaint-nodes#71]
When I run I encounter the following problem and cannot resolve it.Ask for help.

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\SD\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
Requested to load AutoencoderKL
Loading 1 new model
[comfyui-inpaint-nodes] Injecting patched comfy.model_patcher.ModelPatcher.calculate_weight
Requested to load SDXL
Loading 1 new model
!!! Exception during processing!!! ApplyFooocusInpaint._input_block_patch() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "D:\SD\ComfyUI-aki-v1.2\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\SD\ComfyUI-aki-v1.2\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\SD\ComfyUI-aki-v1.2\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\SD\ComfyUI-aki-v1.2\nodes.py", line 1371, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\SD\ComfyUI-aki-v1.2\nodes.py", line 1341, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\SD\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\SD\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 241, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 795, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 697, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 684, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 663, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 568, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\SD\ComfyUI-aki-v1.2\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\k_diffusion\sampling.py", line 732, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "D:\SD\ComfyUI-aki-v1.2\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\k_diffusion\sampling.py", line 635, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 291, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 650, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 653, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 277, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\SD\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_batch
    return calc_cond_batch_original_tiled_diffusion_d4224f5d(model, conds, x_in, timestep, model_options)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\samplers.py", line 226, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\SD\ComfyUI-aki-v1.2\comfy\model_base.py", line 113, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\SD\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\SD\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SD\ComfyUI-aki-v1.2\custom_nodes\FreeU_Advanced\nodes.py", line 184, in __temp__forward
    h, hsp = p(h, hsp, transformer_options)
TypeError: ApplyFooocusInpaint._input_block_patch() takes 3 positional arguments but 4 were given

Prompt executed in 21.92 seconds

**Comment by Acly** [comment]
Looks like in issue with https://github.com/WASasquatch/FreeU_Advanced, maybe you need to update it?
